name: .NET Test and Docker Build

on:
  push:
    branches: [ "main" ]
    tags:
      - '*-v*.*.*'
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:
    inputs:
      service:
        description: 'Which service should the snapshot build be taken for?'
        required: true
        type: choice
        options:
          - frontend
          - identityservice
          - debtservice
          - calculationservice
          - apigateway

jobs:
  test:
    name: 1. Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: .NET 8 Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore debt_payment_backend/debt_payment_backend.sln

    - name: Build
      run: dotnet build debt_payment_backend/debt_payment_backend.sln --no-restore
      
    - name: Run Tests
      run: dotnet test debt_payment_backend/debt_payment_backend.sln --no-build --verbosity normal

  push_release_image:
    name: 2. Versioned Release Push
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Parse the Git Tag
        run: |
          TAG_NAME=${{ github.ref_name }}
          SERVICE_NAME=$(echo $TAG_NAME | cut -d'-' -f1)
          IMAGE_TAG=$(echo $TAG_NAME | cut -d'-' -f2-)
          
          echo "service_name=$SERVICE_NAME" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Build and push Service
        run: |
          SERVICE_NAME=${{ steps.parse_tag.outputs.service_name }}
          IMAGE_TAG=${{ steps.parse_tag.outputs.image_tag }}
          DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          
          echo "Building $SERVICE_NAME with tag $IMAGE_TAG"

          if [ "$SERVICE_NAME" == "frontend" ]; then
            echo "NEXT_PUBLIC_API_URL=http://localhost:5000" >> $GITHUB_ENV
            docker build --build-arg NEXT_PUBLIC_API_URL=http://localhost:5000 -t $DOCKER_USERNAME/frontend:$IMAGE_TAG -f ./debt_payment_frontend/Dockerfile ./debt_payment_frontend            
            docker push $DOCKER_USERNAME/frontend:$IMAGE_TAG
            
          elif [ "$SERVICE_NAME" == "identityservice" ]; then
            docker build -t $DOCKER_USERNAME/identityservice:$IMAGE_TAG -f ./debt_payment_backend/IdentityService/Dockerfile ./debt_payment_backend
            docker push $DOCKER_USERNAME/identityservice:$IMAGE_TAG
            
          elif [ "$SERVICE_NAME" == "debtservice" ]; then
            docker build -t $DOCKER_USERNAME/debtservice:$IMAGE_TAG -f ./debt_payment_backend/DebtService/Dockerfile ./debt_payment_backend
            docker push $DOCKER_USERNAME/debtservice:$IMAGE_TAG
            
          elif [ "$SERVICE_NAME" == "calculationservice" ]; then
            docker build -t $DOCKER_USERNAME/calculationservice:$IMAGE_TAG -f ./debt_payment_backend/CalculationService/Dockerfile ./debt_payment_backend
            docker push $DOCKER_USERNAME/calculationservice:$IMAGE_TAG
            
          elif [ "$SERVICE_NAME" == "apigateway" ]; then
            docker build -t $DOCKER_USERNAME/apigateway:$IMAGE_TAG -f ./debt_payment_backend/ApiGateway/Dockerfile ./debt_payment_backend
            docker push $DOCKER_USERNAME/apigateway:$IMAGE_TAG
            
          else
            echo "::error::Unknown Service Name: $SERVICE_NAME"
            exit 1
          fi
  
  push_snapshot_image:
    name: 3. Push Snapshot
    runs-on: ubuntu-latest
    needs: test

    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name : Checkout (main branch)
        uses: actions/checkout@v4
        with:
          ref: main
        
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get Git SHA and Shorten
        id: get_sha
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build the relevant service and push it as a ‘snapshot’.
        run: |
          SERVICE_NAME=${{ inputs.service }}
          IMAGE_TAG="snapshot-${{ steps.get_sha.outputs.sha }}"
          DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          
          echo "Building $SERVICE_NAME with tag $IMAGE_TAG from main branch"

          if [ "$SERVICE_NAME" == "frontend" ]; then
            docker build -t $DOCKER_USERNAME/frontend:$IMAGE_TAG -f ./debt_payment_frontend/Dockerfile ./debt_payment_frontend
            docker push $DOCKER_USERNAME/frontend:$IMAGE_TAG
            
          elif [ "$SERVICE_NAME" == "identityservice" ]; then
            docker build -t $DOCKER_USERNAME/identityservice:$IMAGE_TAG -f ./debt_payment_backend/IdentityService/Dockerfile ./debt_payment_backend
            docker push $DOCKER_USERNAME/identityservice:$IMAGE_TAG
            
          elif [ "$SERVICE_NAME" == "debtservice" ]; then
            docker build -t $DOCKER_USERNAME/debtservice:$IMAGE_TAG -f ./debt_payment_backend/DebtService/Dockerfile ./debt_payment_backend
            docker push $DOCKER_USERNAME/debtservice:$IMAGE_TAG
            
          elif [ "$SERVICE_NAME" == "calculationservice" ]; then
            docker build -t $DOCKER_USERNAME/calculationservice:$IMAGE_TAG -f ./debt_payment_backend/CalculationService/Dockerfile ./debt_payment_backend
            docker push $DOCKER_USERNAME/calculationservice:$IMAGE_TAG
            
          elif [ "$SERVICE_NAME" == "apigateway" ]; then
            docker build -t $DOCKER_USERNAME/apigateway:$IMAGE_TAG -f ./debt_payment_backend/ApiGateway/Dockerfile ./debt_payment_backend
            docker push $DOCKER_USERNAME/apigateway:$IMAGE_TAG
            
          else
            echo "::error::Unknown Service Name: $SERVICE_NAME"
            exit 1
          fi

  deploy_release:
    name: 4. Deploy Release to Server
    runs-on: ubuntu-latest
    needs: push_release_image
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          
          envs: DOCKER_USERNAME,GITHUB_REF_NAME
          
          script: |
            SERVICE_NAME=$(echo $GITHUB_REF_NAME | cut -d'-' -f1)
            IMAGE_TAG=$(echo $GITHUB_REF_NAME | cut -d'-' -f2-)
            
            export DOCKERHUB_USERNAME=$DOCKER_USERNAME
            export IMAGE_TAG=$IMAGE_TAG

            echo "Deploying $SERVICE_NAME with tag $IMAGE_TAG on Server..."

            cd /opt/debt-calculator
            
            docker compose pull $SERVICE_NAME
            
            docker compose up -d --no-deps $SERVICE_NAME
            
            docker image prune -f
